#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Produces random brain-state values (focus, stress, energy) at a fixed rate."""

import gc
import json
import logging
import time

import numpy as np # used for generating random values

from brand import BRANDNode


class BrainSim(BRANDNode):
    def __init__(self):
        super().__init__() # go back to parent class to initialize

        self.output_stream = self.parameters['output_stream'] # self.parameters is defined in the graph yaml
        self.sample_rate   = int(self.parameters['sample_rate']) # save as the format of int
        self.max_len       = int(self.parameters['max_len'])

        #get the random seed from the parameters
        #if it exists, otherwise set to None
        seed = self.parameters.get('random_seed', None) 
        if seed is not None:
            np.random.seed(int(seed))
            # random_seed: 42
            # seed = 42
            # np.random.seed(42) prepare a random number generator
            # np.random.seed is a function that sets the seed for numpy's random number generator. By setting the seed, you ensure that the sequence of random numbers generated by numpy is reproducible. In this case, if the 'random_seed' parameter is provided, it will be converted to an integer and used to seed the random number generator. This means that every time you run the program with the same seed, you will get the same sequence of random numbers, which can be useful for debugging or testing purposes.

        self.sync_key = self.parameters['sync_key']
        self.time_key = self.parameters['time_key']

        self.period_ns = int(1e9 / self.sample_rate) # calculate the period in nanoseconds
        self.start_ns  = time.monotonic_ns()
        # set start_ns to current time in ns

        self.i = np.uint32(0)
        # i as counter, intialized to 0
        # np.unit32 is a data type: unsigned 32-bit integers

        # Print a log message showing where this node will write data,
        # how fast it will generate samples, and which random seed is used.
        logging.info(
            f"brain_sim: writing to '{self.output_stream}' at {self.sample_rate} Hz "
            f"(period {self.period_ns} ns, seed={seed})"
        )
        # initialing the BrainSim node
        # reads parameters from graph yaml file, sets them as attributes of the node
        # initialize the counter
        # also logs this information


        # __init__(self) is called only for once when the node is created
        # work(self) is called reaptedly with the period defined before
        # every time work(self) is called, it generates random values for focus, stress, and energy

    def work(self):
        # generating the numbers for focus, stress, and energy
        vals = np.round(np.random.uniform(0.0, 1.0, size=3), 1).astype(np.float32)
        # np.random.uniform(0.0, 1.0, size=3) generates 3 random numbers between 0 and 1
        # np.round(..., 1) rounds the numbers to 1 decimal place
        # [0.37454012, 0.95071431, 0.73199394] -> [0.4, 1.0, 0.7]
        # .astype(np.float32) converts the numbers to 32-bit floating point format
        # result might be: vals = np.array([0.4, 1.0, 0.7], dtype=np.float32)

        # creating the entry to be written to the Redis stream
        entry = {
            self.time_key: np.uint64(time.monotonic_ns()).tobytes(),
            # np.unit64(...) converts current time to unsigned 64-bit integer format,
            # .tobytes() converts it to bytes format 
            self.sync_key: json.dumps({}),
            # a standard sync metadata field
            # not used in this example.
            'i':      self.i.tobytes(),
            # .tobytes() converts to bytes format
            'focus':  vals[0].tobytes(),
            'stress': vals[1].tobytes(),
            'energy': vals[2].tobytes(),
        }

        # adding entry to the output stream in Redis
        self.r.xadd(
            self.output_stream,
            entry,
            maxlen=self.max_len,
            # save only the most recent [max_len] entries in the stream, older entries will be deleted
            approximate=True,
        )

        # after adding one entry to the stream, increment the counter
        self.i += np.uint32(1)

        # monotonic-deadline pacing: no drift even if work() slips
        next_tick = self.start_ns + int(self.i) * self.period_ns
        # calculated the time for next rick to run work()
        sleep_s = (next_tick - time.monotonic_ns()) / 1e9
        # calculate the time for sleep
        if sleep_s > 0:
            time.sleep(sleep_s)
            # sleep if the time for the next tick has not arrived yet

# real start of the program
if __name__ == "__main__":
    gc.disable() # to improve performance by disabling garbage collection
    node = BrainSim() # initializing the BrainSim node
    node.run()
    gc.collect() # After the node stops, manually collect unused memory.
