#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Reads brain_state entries from Redis and emits a labeled state."""

import gc
import logging
import time

import numpy as np

from brand import BRANDNode

# create a filter to decode the brain state values (generated by brain_sim node, saved in Redis) into a labeled state
def decode_state(focus, stress, energy):
    if focus > 0.7 and stress < 0.3 and energy > 0.5:
        return "engaged"
    if stress > 0.7:
        return "overwhelmed"
    if energy < 0.3:
        return "tired"
    if focus < 0.4:
        return "distracted"
    return "neutral"


class StateDecoder(BRANDNode):
    def __init__(self):
        super().__init__()

        self.input_stream  = self.parameters['input_stream'].encode() 
        # .encode convert string to bytes
        # the attribute input_stream now is b'brain_state'
        self.output_stream = self.parameters['output_stream']
        # attribute output_stream is str[decoded_state] 
        # do not encode output_stream because 1. logging it later 2. xadd will encode it automatically
        self.max_len       = int(self.parameters['max_len'])
        self.print_states  = bool(self.parameters.get('print_states', True))

        self.sync_key = self.parameters['sync_key'].encode()
        # used later for reading the fields
        # Convert to bytes because Redis stream entries use byte keys.

        self.time_key = self.parameters['time_key']
        
        self.sample_dict = {self.input_stream: '$'}
        # self.input_stream here is b'brain_state'
        # so self.sample_dict = {a binary stuff: '$'}
        # is used for xread later, encode the input stream name to bytes to match Redis's default byte format.
        # $ means we want to read only new entries that arrive after we start reading, not the existing ones.

        logging.info(
            f"state_decoder: reading '{self.input_stream.decode()}' -> " # decode back to string for logging
            f"writing '{self.output_stream}'"
        )

    def work(self):
        sample = self.r.xread(self.sample_dict, block=0)
        # sample = self.r.xread({b'brain_state': '$'}, block=0)
        # sample
        #   └── stream
        #        └── entry
        #            ├── entry_id
        #            └── fields/data
        
        for entry_id, fields in sample[0][1]: # sample[0] is the entry id, sample[1] is the fields
            focus  = float(np.frombuffer(fields[b'focus'],  dtype=np.float32)[0])
            # b'focus' is because the field is written in bytes in Redis in brain_sim node
            # dtype=np.float32 is to have the field written back as flaot32
            # np.frombuffer() is to convert the bytes back to a numpy array
            # and [0] is to get the scalar value from the array， even though it's just one value, it will be in an array of size 1
            stress = float(np.frombuffer(fields[b'stress'], dtype=np.float32)[0])
            energy = float(np.frombuffer(fields[b'energy'], dtype=np.float32)[0])
            i_val  = int(np.frombuffer(fields[b'i'], dtype=np.uint32)[0])

            # get the value for focus, stress, energy from the fields, convert from bytes to float

            state = decode_state(focus, stress, energy)
            # determine the state

            # recreate the entry to write into Redis, add the decoded state
            out_entry = {
                self.time_key: np.uint64(time.monotonic_ns()).tobytes(),
                self.sync_key: fields[self.sync_key],
                'i':      fields[b'i'],
                'state':  state.encode('utf-8'),
                'focus':  fields[b'focus'],
                'stress': fields[b'stress'],
                'energy': fields[b'energy'],
            }
            self.r.xadd(
                self.output_stream,
                out_entry,
                maxlen=self.max_len,
                approximate=True,
            )

            if self.print_states:
                logging.info(
                    f"i={i_val} focus={focus:.1f} stress={stress:.1f} "
                    f"energy={energy:.1f} -> {state}"
                )

        self.sample_dict[self.input_stream] = sample[0][1][-1][0]
        # sample[0][1][-1][0] is the entry id of the last entry we just processed
        # so sample_dict is updated to {b'brain_state': last_entry_id}


if __name__ == "__main__":
    gc.disable()
    node = StateDecoder()
    node.run()
    gc.collect()

# for writing into Redis, using xadd, string is ok
# for reading from Redis, using xread, better to encode
